-- TRUNCATE TABLE fine_dm.dm_distributor_target_report;
-- insert into fine_dm.dm_distributor_target_report -- dm_distributor_target_report

WITH  temp_001 as (
select *
from  fine_dw.dw_distributor_sales_target 
 WHERE target_year =${mysql_yesterday_d_year}
-- WHERE target_year ='2022'
)



SELECT s.*,
      STR_TO_DATE(CONCAT( target_year,'0101') , '%Y%m%d') as report_date
 FROM(
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'By Quarter') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'By Quarter'AS sec_2,'Q1'AS sec_3,Q1 AS sales_target, 1 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'By Quarter') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'By Quarter'AS sec_2,'Q2'AS sec_3,Q2 AS sales_target, 2 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'By Quarter') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'By Quarter'AS sec_2,'Q3'AS sec_3,Q3 AS sales_target, 3 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'By Quarter') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'By Quarter'AS sec_2,'Q4'AS sec_3,Q4 AS sales_target, 4 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'By Quarter') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'By Quarter'AS sec_2,'Total'AS sec_3,total_ze AS sales_target, 5 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'高档水性EHP/AQ+/AUTOMOTIVE WB'AS sec_3,gdsxq_1 AS sales_target, 6 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'高档油性AC/GRS'AS sec_3,gdyxq_1 AS sales_target, 7 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'中档水性QUICKLINE'AS sec_3,quickline_1 AS sales_target, 8 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'中档油性EMAXX'AS sec_3,emaxx_1 AS sales_target, 9 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'中档油性BELCO PLUS'AS sec_3,belco_1 AS sales_target, 10 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'原子灰'AS sec_3,yzh_1 AS sales_target, 11 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'易耗品'AS sec_3,yhp_1 AS sales_target, 12 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'AUTOMOTIVE WB全水性漆'AS sec_3,qsx_1 AS sales_target, 13 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'凌趣惠管站软件'AS sec_3,lqhg_1 AS sales_target, 14 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q1') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q1'AS sec_2,'Total'AS sec_3,total_1 AS sales_target, 15 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'高档水性EHP/AQ+/AUTOMOTIVE WB'AS sec_3,gdsxq_2 AS sales_target, 16 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'高档油性AC/GRS'AS sec_3,gdyxq_2 AS sales_target, 17 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'中档水性QUICKLINE'AS sec_3,quickline_2 AS sales_target, 18 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'中档油性EMAXX'AS sec_3,emaxx_2 AS sales_target, 19 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'中档油性BELCO PLUS'AS sec_3,belco_2 AS sales_target, 20 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'原子灰'AS sec_3,yzh_2 AS sales_target, 21 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'易耗品'AS sec_3,yhp_2 AS sales_target, 22 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'AUTOMOTIVE WB全水性漆'AS sec_3,qsx_2 AS sales_target, 23 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'凌趣惠管站软件'AS sec_3,lqhg_2 AS sales_target, 24 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q2') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q2'AS sec_2,'Total'AS sec_3,total_2 AS sales_target, 25 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'高档水性EHP/AQ+/AUTOMOTIVE WB'AS sec_3,gdsxq_3 AS sales_target, 26 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'高档油性AC/GRS'AS sec_3,gdyxq_3 AS sales_target, 27 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'中档水性QUICKLINE'AS sec_3,quickline_3 AS sales_target, 28 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'中档油性EMAXX'AS sec_3,emaxx_3 AS sales_target, 29 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'中档油性BELCO PLUS'AS sec_3,belco_3 AS sales_target, 30 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'原子灰'AS sec_3,yzh_3 AS sales_target, 31 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'易耗品'AS sec_3,yhp_3 AS sales_target, 32 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'AUTOMOTIVE WB全水性漆'AS sec_3,qsx_3 AS sales_target, 33 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'凌趣惠管站软件'AS sec_3,lqhg_3 AS sales_target, 34 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q3') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q3'AS sec_2,'Total'AS sec_3,total_3 AS sales_target, 35 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'高档水性EHP/AQ+/AUTOMOTIVE WB'AS sec_3,gdsxq_4 AS sales_target, 36 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'高档油性AC/GRS'AS sec_3,gdyxq_4 AS sales_target, 37 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'中档水性QUICKLINE'AS sec_3,quickline_4 AS sales_target, 38 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'中档油性EMAXX'AS sec_3,emaxx_4 AS sales_target, 39 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'中档油性BELCO PLUS'AS sec_3,belco_4 AS sales_target, 40 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'原子灰'AS sec_3,yzh_4 AS sales_target, 41 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'易耗品'AS sec_3,yhp_4 AS sales_target, 42 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'AUTOMOTIVE WB全水性漆'AS sec_3,qsx_4 AS sales_target, 43 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'凌趣惠管站软件'AS sec_3,lqhg_4 AS sales_target, 44 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,'Q4') as target_quarter,CONCAT(target_year,' Target') AS sec_1,'Q4'AS sec_2,'Total'AS sec_3,total_4 AS sales_target, 45 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'高档水性EHP/AQ+/AUTOMOTIVE WB'AS sec_3,full_year_gdsxq AS sales_target, 46 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'高档油性AC/GRS'AS sec_3,full_year_gdyxq AS sales_target, 47 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'中档水性QUICKLINE'AS sec_3,full_year_quickline AS sales_target, 48 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'中档油性EMAXX'AS sec_3,full_year_emaxx AS sales_target, 49 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'中档油性BELCO PLUS'AS sec_3,full_year_belco AS sales_target, 50 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'原子灰'AS sec_3,full_year_yzh AS sales_target, 51 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'易耗品'AS sec_3,full_year_yhp AS sales_target, 52 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'AUTOMOTIVE WB全水性漆'AS sec_3,full_year_qsx AS sales_target, 53 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'凌趣惠管站软件'AS sec_3,full_year_lqhg AS sales_target, 54 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001 UNION ALL
SELECT customer_code,district,team_owner,team_owner_id,sales_person,sales_person_id,customer_name,target_year,CONCAT(target_year,CONCAT('FY ',target_year)) as target_quarter,CONCAT(target_year,' Target') AS sec_1,CONCAT('FY ',target_year)AS sec_2,'Total'AS sec_3,full_year_total AS sales_target, 55 AS order_no, 'dw_distributor_sales_target' as data_resource,SYSDATE() as etl_time  FROM temp_001						
)s where customer_code is not null		
						