SELECT
	_id,
	REPLACE(JSON_EXTRACT(creator, '$.name'), '"', '')  as creator,
	updateTime,
	flowState,
	REPLACE(JSON_EXTRACT(deleter, '$.name'), '"', '')  as deleter,
	REPLACE(JSON_EXTRACT(updater, '$.name'), '"', '')  as updater,
	createTime,
	deleteTime,
	dawn_name,
	mso_name,
	YEAR,
	 REPLACE(JSON_EXTRACT(sales, '$.name'), '"', '')  as sales_name,
	REPLACE(JSON_EXTRACT(sales, '$.username'), '"', '')  as sales_code,
	number,
	dawn_id,
	MONTH,
	date,
	distributor_id,
	ppg_volume,
	distributor_name,
	enclosure_number,
	invoice,
	REPLACE(JSON_EXTRACT(department, '$.name'), '"', '')  as department,
	REPLACE(JSON_EXTRACT(USER, '$.name'), '"', '')  as USER,
	sales_volume,
	'jxsmdxssjsqb' as data_resource,
	NOW() as etl_time
FROM
	fine_ods.jxsmdxssjsqb